modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
config="bestflashlight.mixins.json"

[[mods]]
modId="bestflashlight"
version="${mod_version}"
displayName="Flashlight FE"
authors="LTDigor"
description='''A rechargeable handheld flashlight with a removable headband mount, directional lighting, and Curios support.'''

[[dependencies.bestflashlight]]
modId="neoforge"
type="required"
versionRange="[21.1.249,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.bestflashlight]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.bestflashlight]]
modId="curios"
type="required"
versionRange="[9.5.1,10)"
ordering="AFTER"
side="BOTH"

[[dependencies.bestflashlight]]
modId="jei"
type="optional"
versionRange="[19.18,20)"
ordering="AFTER"
side="CLIENT"
